INSERT INTO location (Town, PostCode) VALUES
('Berlin', 10115),
('München', 80331),
('Hamburg', 20095),
('Köln', 50667),
('Frankfurt am Main', 60311),
('Stuttgart', 70173),
('Düsseldorf', 40213),
('Dortmund', 44135),
('Essen', 45127),
('Leipzig', 04109),
('Bremen', 28195),
('Dresden', 01067),
('Hannover', 30159),
('Nürnberg', 90402),
('Duisburg', 47051),
('Bochum', 44787),
('Wuppertal', 42103),
('Bielefeld', 33602),
('Bonn', 53111),
('Münster', 48143);

INSERT INTO user (Email, Name, Privileges, TutorialStep, Password, LocationId, ProfileId) VALUES
('user1@example.com', 'Max Mustermann', 'user', 1, 'pass1234', 1, NULL),
('user2@example.com', 'Erika Musterfrau', 'user', 2, 'pass1234', 2, NULL),
('user3@example.com', 'Johannes Vogel', 'admin', 3, 'pass1234', 3, NULL),
('user4@example.com', 'Sophie Schmitt', 'user', 4, 'pass1234', 4, NULL),
('user5@example.com', 'Alexander Klein', 'user', 5, 'pass1234', 5, NULL),
('user6@example.com', 'Maria Koch', 'user', 1, 'pass1234', 6, NULL),
('user7@example.com', 'Christian Wolf', 'user', 2, 'pass1234', 7, NULL),
('user8@example.com', 'Julia Hartmann', 'admin', 3, 'pass1234', 8, NULL),
('user9@example.com', 'Tobias Krüger', 'user', 4, 'pass1234', 9, NULL),
('user10@example.com', 'Laura Neumann', 'user', 5, 'pass1234', 10, NULL),
('user11@example.com', 'Sebastian Schäfer', 'user', 1, 'pass1234', 11, NULL),
('user12@example.com', 'Annika Bäcker', 'user', 2, 'pass1234', 12, NULL),
('user13@example.com', 'Niklas Schwarz', 'admin', 3, 'pass1234', 13, NULL),
('user14@example.com', 'Lena Meyer', 'user', 4, 'pass1234', 14, NULL),
('user15@example.com', 'Finn Bauer', 'user', 5, 'pass1234', 15, NULL),
('user16@example.com', 'Emilia Schneider', 'user', 1, 'pass1234', 16, NULL),
('user17@example.com', 'Leon Zimmermann', 'user', 2, 'pass1234', 17, NULL),
('user18@example.com', 'Mia Lange', 'admin', 3, 'pass1234', 18, NULL),
('user19@example.com', 'Lukas Hofmann', 'user', 4, 'pass1234', 19, NULL),
('user20@example.com', 'Charlotte Fischer', 'user', 5, 'pass1234', 20, NULL);

INSERT INTO picture (Filename) VALUES
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL);

INSERT INTO advertisement (Title, Content, AdCategory, `Condition`, Periods, Price, Discriminator, UserId, LocationId, PictureId) VALUES
('Vintage Ledersofa', 'Gebrauchtes Ledersofa in gutem Zustand.', 'Möbel', 'Gebraucht', '2024-04-16 12:00:00', 250.00, 'Ware', 1, 1, NULL),
('Webdesign Services', 'Professionelle Webdesign und Entwicklungsdienste.', 'Services', 'Neu', '2024-06-16 13:00:00', 500.00, 'Dienstleistung', 2, 2, NULL),
('Mountainbike fast neu', 'Hochwertiges Mountainbike, kaum benutzt.', 'Sport', 'Wie Neu', '2024-05-16 14:00:00', 800.00, 'Ware', 3, 3, NULL),
('Reinigungsdienst', 'Biete Reinigungsdienst für Büros und Privathaushalte.', 'Haushalt', 'Neu', '2024-07-16 15:00:00', 100.00, 'Dienstleistung', 4, 4, NULL),
('Gebrauchtwagen Volkswagen', 'Zuverlässiger Gebrauchtwagen in gutem Zustand.', 'Auto', 'Gebraucht', '2024-08-16 16:00:00', 5000.00, 'Ware', 5, 5, NULL),
('Fotografie Dienstleistungen', 'Biete professionelle Fotografie für Veranstaltungen.', 'Dienstleistungen', 'Neu', '2024-09-16 17:00:00', 300.00, 'Dienstleistung', 6, 6, NULL),
('Antike Uhr', 'Schöne antike Uhr, voll funktionsfähig.', 'Antiquitäten', 'Gebraucht', '2024-10-16 18:00:00', 450.00, 'Ware', 7, 7, NULL),
('Yoga Unterricht', 'Biete Yoga Unterricht für Anfänger und Fortgeschrittene.', 'Sport', 'Neu', '2024-11-16 19:00:00', 15.00, 'Dienstleistung', 8, 8, NULL),
('Designer Couchtisch', 'Modernes Design, ideal für jedes Wohnzimmer.', 'Möbel', 'Neu', '2024-12-16 20:00:00', 200.00, 'Ware', 9, 9, NULL),
('Mathematik Nachhilfe', 'Erfahrene Lehrkraft bietet Mathematik Nachhilfe.', 'Bildung', 'Neu', '2025-01-16 21:00:00', 20.00, 'Dienstleistung', 10, 10, NULL),
('Espressomaschine', 'Hochwertige Espressomaschine, perfekter Zustand.', 'Haushaltsgeräte', 'Wie Neu', '2024-04-17 10:00:00', 100.00, 'Ware', 11, 11, NULL),
('Softwareentwicklung Freelancer', 'Biete Freelance Dienste in Softwareentwicklung.', 'IT', 'Neu', '2024-05-17 11:00:00', 1000.00, 'Dienstleistung', 12, 12, NULL),
('Elektrisches Klavier', 'Fast neues elektrisches Klavier, ideal für Anfänger.', 'Musikinstrumente', 'Wie Neu', '2024-06-17 12:00:00', 600.00, 'Ware', 13, 13, NULL),
('Haustierbetreuung', 'Zuverlässige Betreuung für Ihre Haustiere.', 'Haustier', 'Neu', '2024-07-17 13:00:00', 50.00, 'Dienstleistung', 14, 14, NULL),
('Spielkonsole', 'Neuwertige Spielkonsole, kaum benutzt.', 'Elektronik', 'Wie Neu', '2024-08-17 14:00:00', 250.00,  'Ware', 15, 15, NULL),
('Umzugsservice', 'Biete schnellen und zuverlässigen Umzugsservice.', 'Umzug', 'Neu', '2024-09-17 15:00:00', 400.00, 'Dienstleistung', 16, 16, NULL),
('Digitalkamera',  'Hochauflösende Digitalkamera, ideal für Hobbyfotografen.', 'Fotografie', 'Gebraucht', '2024-10-17 16:00:00', 150.00, 'Ware', 17, 17, NULL),
('Programmierkurse',  'Online-Programmierkurse für Anfänger und Fortgeschrittene.', 'Bildung', 'Neu', '2024-11-17 17:00:00', 200.00,'Dienstleistung', 18, 18, NULL),
('Smartphone', 'Neuestes Modell, unbenutzt und noch verpackt.', 'Elektronik', 'Neu', '2024-12-17 18:00:00', 800.00, 'Ware', 19, 19, NULL),
('Sprachunterricht', 'Biete individuellen Sprachunterricht online.', 'Dienstleistungen', 'Neu', '2025-01-17 19:00:00', 25.00, 'Dienstleistung', 20, 20, NULL);

INSERT INTO message (Content, UserIdFrom, UserIdTo, PictureId) VALUES
('Hallo, wie war dein Tag?', 1, 2, NULL),
('Kannst du mir bei meinem Projekt helfen?', 2, 3, NULL),
('Ich habe tolle Neuigkeiten zu teilen!', 3, 4, NULL),
('Erinnerst du dich an unser Treffen morgen?', 4, 5, NULL),
('Ich bin nächste Woche in deiner Stadt. Treffen?', 5, 1, NULL),
('Wie geht es deinem Haustier?', 1, 3, NULL),
('Hast du Lust auf Kino am Wochenende?', 3, 2, NULL),
('Kannst du mir das Rezept von letztem Mal schicken?', 2, 4, NULL),
('Lass uns für das Projekt morgen online treffen.', 4, 3, NULL),
('Brauchst du Hilfe bei der Präsentation?', 3, 5, NULL),
('Wir müssen unser Treffen leider verschieben.', 5, 1, NULL),
('Wie läuft deine Arbeit?', 1, 4, NULL),
('Hast du den Artikel gelesen, den ich geschickt habe?', 4, 2, NULL),
('Wir sollten bald wieder joggen gehen.', 2, 5, NULL),
('Wie war deine Prüfung?', 5, 3, NULL),
('Vergiss nicht, morgen den Vertrag zu unterschreiben.', 3, 1, NULL),
('Ich habe ein neues Buch, das dir gefallen könnte.', 1, 2, NULL),
('Kann ich dir etwas aus der Stadt mitbringen?', 2, 3, NULL),
('Wollen wir nächste Woche zum Sport?', 3, 4, NULL),
('Wie steht es um unser Projekt?', 4, 5, NULL);

INSERT INTO notification ( Content, UserId, AdvertisementId, ChatMessageId) VALUES
('Willkommen bei unserer Plattform!', 1, NULL, NULL),
('Deine Anzeige wurde veröffentlicht.', NULL, 1, NULL),
('Du hast eine neue Nachricht.', NULL, NULL, 1),
('Denke daran, dein Profil zu aktualisieren.', 2, NULL, NULL),
('Jemand hat dein Produkt angefragt.', NULL, 2, NULL),
('Ein Freund hat dir eine Nachricht geschickt.', NULL, NULL, 2),
('Neue Tipps für dein Profil!', 3, NULL, NULL),
('Deine Anzeige hat eine hohe Sichtbarkeit erreicht.', NULL, 3, NULL),
('Du wurdest zu einem Gruppenchat hinzugefügt.', NULL, NULL, 3),
('Aktualisiere deine Einstellungen für personalisierte Anzeigen.', 4, NULL, NULL),
('Dein Verkaufsangebot läuft bald aus.', NULL, 4, NULL),
('Ein neuer Kommentar in deinem Chat.', NULL, NULL, 4),
('Erhalte mehr Sichtbarkeit mit Premium!', 5, NULL, NULL),
('Eine Bewertung wurde zu deiner Anzeige hinzugefügt.', NULL, 5, NULL),
('Ein Nutzer hat deine Nachricht gelesen.', NULL, NULL, 5),
('Neue Sicherheitsfeatures verfügbar.', 6, NULL, NULL),
('Deine Anzeige wurde aktualisiert.', NULL, 6, NULL),
('Du hast eine neue Freundschaftsanfrage.', NULL, NULL, 6),
('Verpasse nicht die neuesten Angebote.', 7, NULL, NULL),
('Ein Käufer ist interessiert an deinem Angebot.', NULL, 7, NULL);

INSERT INTO profile (FirstName, LastName, Description, PictureId) VALUES
('Max', 'Mustermann', 'Liebhaber von Büchern und Kaffee.', NULL),
('Erika', 'Musterfrau', 'Begeisterte Wanderin und Fotografin.', NULL),
('Julian', 'Baum', 'Software-Entwickler mit einer Leidenschaft für Musik.', NULL),
('Sophia', 'Berg', 'Freiberufliche Designerin und Kunstliebhaberin.', NULL),
('Lukas', 'Feld', 'Digital Marketing Spezialist und Reiseblogger.', NULL),
('Mia', 'Welle', 'Yoga-Lehrerin und Nachhaltigkeits-Befürworterin.', NULL),
('Noah', 'Fluss', 'Startup-Gründer im Bereich der erneuerbaren Energien.', NULL),
('Emma', 'Wald', 'Kreative Schriftstellerin und Poetin.', NULL),
('Ben', 'Himmel', 'Amateur-Astronom und Physik-Enthusiast.', NULL),
('Anna', 'Stern', 'Architektin mit einem Auge für moderne Kunst.', NULL),
('Finn', 'Stein', 'Landschaftsarchitekt und Umweltschützer.', NULL),
('Lena', 'Wiese', 'Professionelle Tänzerin und Choreografin.', NULL),
('Paul', 'Sand', 'Leidenschaftlicher Koch und Food-Blogger.', NULL),
('Laura', 'Mond', 'Dokumentarfilmerin mit Fokus auf soziale Themen.', NULL),
('Jonas', 'Blatt', 'Biologe und Naturschützer.', NULL),
('Emily', 'Blume', 'Mode-Designerin mit einem Hang zu nachhaltiger Mode.', NULL),
('Leon', 'Wasser', 'Surflehrer und Meeresliebhaber.', NULL),
('Marie', 'Vogel', 'Veterinärmedizinerin und Tierrechtsaktivistin.', NULL),
('Felix', 'Licht', 'Fotograf mit Spezialisierung auf Landschafts- und Stadtbilder.', NULL),
('Charlotte', 'Nacht', 'DJane und Musikproduzentin im Elektronik-Bereich.', NULL);

INSERT INTO review (Title, UserId, Stars, Content) VALUES
('Toller Service', 1, 5, 'Ich bin sehr zufrieden mit dem Service. Alles lief reibungslos.'),
('Wunderbares Produkt', 2, 4, 'Das Produkt übertraf meine Erwartungen. Sehr empfehlenswert!'),
('Nicht zufrieden', 3, 2, 'Das Produkt kam beschädigt an und der Kundenservice war nicht hilfreich.'),
('Könnte besser sein', 4, 3, 'Insgesamt in Ordnung, aber es gibt definitiv Raum für Verbesserungen.'),
('Fantastisches Erlebnis', 5, 5, 'Von Anfang bis Ende ein fantastisches Erlebnis. Würde es definitiv empfehlen.'),
('Überbewertet', 6, 2, 'Ich verstehe den Hype nicht. Das Produkt erfüllte nicht meine Erwartungen.'),
('Solide Leistung', 7, 4, 'Guter Wert für den Preis. Die Leistung ist solide.'),
('Problem gelöst', 8, 4, 'Es gab ein kleines Problem, aber der Kundenservice hat es schnell gelöst.'),
('Unterdurchschnittlich', 9, 2, 'Die Qualität ist unterdurchschnittlich. Nicht das, was ich erwartet hatte.'),
('Ausgezeichneter Kauf', 10, 5, 'Einer meiner besten Käufe. Hochwertig und zuverlässig.'),
('Mittelmäßig', 11, 3, 'Nicht schlecht, aber auch nicht herausragend. Mittelmäßig.'),
('Sehr enttäuscht', 12, 1, 'Erwartungen nicht erfüllt. Sehr enttäuscht von der Erfahrung.'),
('Großartiger Support', 13, 5, 'Der Kundensupport war ausgezeichnet. Schnelle und effektive Hilfe.'),
('Einfach ok', 14, 3, 'Nichts Besonderes, aber auch nicht schrecklich. Einfach ok.'),
('Preis-Leistungs-Verhältnis', 15, 4, 'Für den Preis ein sehr gutes Produkt. Zufrieden mit dem Kauf.'),
('Lange Lieferzeit', 16, 2, 'Das Produkt ist in Ordnung, aber die Lieferzeit war viel zu lang.'),
('Hervorragende Qualität', 17, 5, 'Die Qualität ist hervorragend. Übertrifft definitiv die Erwartungen.'),
('Nicht empfohlen', 18, 1, 'Ich würde dieses Produkt oder Service nicht empfehlen.'),
('Zufriedenstellend', 19, 4, 'Insgesamt bin ich zufrieden mit meinem Kauf. Gute Erfahrung.'),
('Verbesserung benötigt', 20, 2, 'Das Konzept ist gut, aber die Umsetzung könnte besser sein.');


INSERT INTO user_advertisement (UserId, AdvertisementId) VALUES
(1, 1),
(1, 3),
(2, 2),
(2, 4),
(3, 5),
(3, 7),
(4, 6),
(4, 8),
(5, 9),
(5, 11),
(6, 12),
(6, 13),
(7, 14),
(7, 16),
(8, 17),
(8, 18),
(9, 19),
(9, 1),
(10, 2),
(10, 4);
