INSERT INTO profile (FirstName, LastName, Description, PictureId) VALUES
('Max', 'Mustermann', 'Liebhaber von Büchern und Kaffee.', NULL),
('Erika', 'Musterfrau', 'Begeisterte Wanderin und Fotografin.', NULL),
('Julian', 'Baum', 'Software-Entwickler mit einer Leidenschaft für Musik.', NULL),
('Sophia', 'Berg', 'Freiberufliche Designerin und Kunstliebhaberin.', NULL),
('Lukas', 'Feld', 'Digital Marketing Spezialist und Reiseblogger.', NULL),
('Mia', 'Welle', 'Yoga-Lehrerin und Nachhaltigkeits-Befürworterin.', NULL),
('Noah', 'Fluss', 'Startup-Gründer im Bereich der erneuerbaren Energien.', NULL),
('Emma', 'Wald', 'Kreative Schriftstellerin und Poetin.', NULL),
('Ben', 'Himmel', 'Amateur-Astronom und Physik-Enthusiast.', NULL),
('Anna', 'Stern', 'Architektin mit einem Auge für moderne Kunst.', NULL),
('Finn', 'Stein', 'Landschaftsarchitekt und Umweltschützer.', NULL),
('Lena', 'Wiese', 'Professionelle Tänzerin und Choreografin.', NULL),
('Paul', 'Sand', 'Leidenschaftlicher Koch und Food-Blogger.', NULL),
('Laura', 'Mond', 'Dokumentarfilmerin mit Fokus auf soziale Themen.', NULL),
('Jonas', 'Blatt', 'Biologe und Naturschützer.', NULL),
('Emily', 'Blume', 'Mode-Designerin mit einem Hang zu nachhaltiger Mode.', NULL),
('Leon', 'Wasser', 'Surflehrer und Meeresliebhaber.', NULL),
('Marie', 'Vogel', 'Veterinärmedizinerin und Tierrechtsaktivistin.', NULL),
('Felix', 'Licht', 'Fotograf mit Spezialisierung auf Landschafts- und Stadtbilder.', NULL),
('Charlotte', 'Nacht', 'DJane und Musikproduzentin im Elektronik-Bereich.', NULL);
