INSERT INTO review (Title, UserId, Stars, Content) VALUES
('Toller Service', 1, 5, 'Ich bin sehr zufrieden mit dem Service. Alles lief reibungslos.'),
('Wunderbares Produkt', 2, 4, 'Das Produkt übertraf meine Erwartungen. Sehr empfehlenswert!'),
('Nicht zufrieden', 3, 2, 'Das Produkt kam beschädigt an und der Kundenservice war nicht hilfreich.'),
('Könnte besser sein', 4, 3, 'Insgesamt in Ordnung, aber es gibt definitiv Raum für Verbesserungen.'),
('Fantastisches Erlebnis', 5, 5, 'Von Anfang bis Ende ein fantastisches Erlebnis. Würde es definitiv empfehlen.'),
('Überbewertet', 6, 2, 'Ich verstehe den Hype nicht. Das Produkt erfüllte nicht meine Erwartungen.'),
('Solide Leistung', 7, 4, 'Guter Wert für den Preis. Die Leistung ist solide.'),
('Problem gelöst', 8, 4, 'Es gab ein kleines Problem, aber der Kundenservice hat es schnell gelöst.'),
('Unterdurchschnittlich', 9, 2, 'Die Qualität ist unterdurchschnittlich. Nicht das, was ich erwartet hatte.'),
('Ausgezeichneter Kauf', 10, 5, 'Einer meiner besten Käufe. Hochwertig und zuverlässig.'),
('Mittelmäßig', 11, 3, 'Nicht schlecht, aber auch nicht herausragend. Mittelmäßig.'),
('Sehr enttäuscht', 12, 1, 'Erwartungen nicht erfüllt. Sehr enttäuscht von der Erfahrung.'),
('Großartiger Support', 13, 5, 'Der Kundensupport war ausgezeichnet. Schnelle und effektive Hilfe.'),
('Einfach ok', 14, 3, 'Nichts Besonderes, aber auch nicht schrecklich. Einfach ok.'),
('Preis-Leistungs-Verhältnis', 15, 4, 'Für den Preis ein sehr gutes Produkt. Zufrieden mit dem Kauf.'),
('Lange Lieferzeit', 16, 2, 'Das Produkt ist in Ordnung, aber die Lieferzeit war viel zu lang.'),
('Hervorragende Qualität', 17, 5, 'Die Qualität ist hervorragend. Übertrifft definitiv die Erwartungen.'),
('Nicht empfohlen', 18, 1, 'Ich würde dieses Produkt oder Service nicht empfehlen.'),
('Zufriedenstellend', 19, 4, 'Insgesamt bin ich zufrieden mit meinem Kauf. Gute Erfahrung.'),
('Verbesserung benötigt', 20, 2, 'Das Konzept ist gut, aber die Umsetzung könnte besser sein.');
