INSERT INTO labswp24ccommunity.advertisement (Title, Time, UserEmail, LocationPostCode, LocationTown, Content, AdCategory, `Condition`, Period, Price, Date, Discriminator, `Column`) VALUES ('Cider', '2023-12-19 11:11:35', 'gerald.permantier@hs-heilbronn.de', null, null, 'Delicious fresh Cider', 'Good', null, null, 0, null, null, null);
INSERT INTO labswp24ccommunity.advertisement (Title, Time, UserEmail, LocationPostCode, LocationTown, Content, AdCategory, `Condition`, Period, Price, Date, Discriminator, `Column`) VALUES ('Fahrrad zum verschenken', '2023-12-13 17:05:44', 'provider@ccommunity.de', 74072, 'Heilbronn', 'Ich verschenke ein gebrauchtes Fahrrad, das ich nicht mehr benötige.', 'Good', null, null, 0, null, 'Good', null);
INSERT INTO labswp24ccommunity.advertisement (Title, Time, UserEmail, LocationPostCode, LocationTown, Content, AdCategory, `Condition`, Period, Price, Date, Discriminator, `Column`) VALUES ('Futter', '2023-12-19 12:33:13', 'gerald.permantier@hs-heilbronn.de', null, null, 'Futter für Katze', 'Good', null, null, 0, null, null, null);
INSERT INTO labswp24ccommunity.advertisement (Title, Time, UserEmail, LocationPostCode, LocationTown, Content, AdCategory, `Condition`, Period, Price, Date, Discriminator, `Column`) VALUES ('Gassi gehen', '2023-12-13 19:07:56', 'provider@ccommunity.de', 74076, 'Heilbronn', 'Ich biete an, morgens und mittags mit Ihrem Hund spazieren zu gehen.', 'Service', null, null, 10, null, 'Service', null);
INSERT INTO labswp24ccommunity.advertisement (Title, Time, UserEmail, LocationPostCode, LocationTown, Content, AdCategory, `Condition`, Period, Price, Date, Discriminator, `Column`) VALUES ('Kartoffeln', '2023-12-19 10:59:35', 'test@ccommunity.de', null, null, 'gute Kartoffeln zu verschenken', 'Good', null, null, 0, null, null, null);
INSERT INTO labswp24ccommunity.advertisement (Title, Time, UserEmail, LocationPostCode, LocationTown, Content, AdCategory, `Condition`, Period, Price, Date, Discriminator, `Column`) VALUES ('Katze', '2023-12-19 12:16:47', 'gerald.permantier@hs-heilbronn.de', null, null, 'Emotional support Cat', 'Service', null, null, 0, null, null, null);
INSERT INTO labswp24ccommunity.advertisement (Title, Time, UserEmail, LocationPostCode, LocationTown, Content, AdCategory, `Condition`, Period, Price, Date, Discriminator, `Column`) VALUES ('Laptop', '2023-12-19 13:03:51', 'gerald.permantier@hs-heilbronn.de', 74321, 'Bietigheim-Bissingen', 'Laptop zu verschenken', 'Good', null, null, 0, null, null, null);
INSERT INTO labswp24ccommunity.advertisement (Title, Time, UserEmail, LocationPostCode, LocationTown, Content, AdCategory, `Condition`, Period, Price, Date, Discriminator, `Column`) VALUES ('Wäsche bügeln', '2023-12-21 16:40:28', 'gerald.permantier@hs-heilbronn.de', null, null, 'Ich bügle ihre Wäsche, egal ob großes oder kleines Format', 'Service', null, null, 15, null, null, null);
INSERT INTO labswp24ccommunity.advertisement (Title, Time, UserEmail, LocationPostCode, LocationTown, Content, AdCategory, `Condition`, Period, Price, Date, Discriminator, `Column`) VALUES ('Wäsche bügeln und legen', '2023-12-21 16:45:36', 'gerald.permantier@hs-heilbronn.de', 74081, 'Heilbronn', 'Ich bügle und lege ihnen schöne glatte Stapel', 'Service', null, null, 17.99, null, null, null);
